<a href="https://colab.research.google.com/github/Sachinsen1295/ML-Models/blob/main/Linear_Regression_Modle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Predict the Price of Banglore House**

Using Linear Regression - Supervised Machine Learning Algorithm

###Load Libraries

In [ ]:

import pandas as pd
from sklearn.model_selection import train_test_split

###Load DataSet

In [ ]:
from google.colab import drive

In [ ]:
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
df= pd.read_csv(r"/content/drive/MyDrive/Colab Notebooks/ML Module/Data For Model/bangalore house price prediction OHE-data.csv")
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

##Split Data

In [ ]:
X= df.drop('price', axis=1)
Y= df['price']

print('shape of X=', X.shape)
print('shape of Y = ' ,Y.shape)

shape of X= (7120, 107)
shape of Y =  (7120,)


In [ ]:
X_train, X_test, Y_train , Y_test = train_test_split(X,Y, test_size=0.2 ,  random_state=51)

print('shape of X=', X_train.shape)
print('shape of Y = ' ,Y_train.shape)
print('shape of X=', X_test.shape)
print('shape of Y = ' ,Y_test.shape)

shape of X= (5696, 107)
shape of Y =  (5696,)
shape of X= (1424, 107)
shape of Y =  (1424,)


# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc= StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

# Linear Regression - ML model trainning


In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [ ]:
lr.fit(X_train,Y_train)

LinearRegression()

In [ ]:
lr.coef_

array([-5.70206143e+00, -1.25679916e+00,  8.27341833e+01, -1.44906911e+01,
        5.75662723e+01,  1.88468905e-01, -1.72593897e+00, -4.51058311e+00,
       -2.22589244e+00, -4.28978455e+00, -2.44590976e+00,  5.40246226e-01,
       -1.03633400e+00,  1.43064873e+00, -6.25029424e-02, -1.51548783e+00,
       -2.14422789e-01,  2.16244155e+00, -1.48710228e+00,  1.95250816e+00,
       -3.10761125e+00, -1.28138668e+00, -1.01367155e+00,  1.37968545e-02,
        1.10383858e+00,  1.26497611e+00, -3.52405517e+00, -1.21398741e+00,
       -5.04622019e-01,  1.46299181e+00, -5.50064233e-01, -8.46468162e-02,
        6.84882188e-01, -1.39849820e+00, -1.94761710e-02, -1.57716300e+00,
        4.20886278e-01,  8.03443207e-01,  2.99182164e+00,  3.86430413e-03,
        1.05037261e-01,  2.89115612e-01, -3.16916626e-01,  1.05625868e+00,
       -1.39649279e+00, -3.10533604e+00,  1.01764011e-01, -7.49672917e-02,
       -8.03271555e-01, -1.27061856e+00, -8.54046164e-01,  2.64566484e-01,
        9.10688839e-01, -

In [ ]:
lr.intercept_

95.0802729985955

##Predict the value of Home and Predict

In [ ]:
X_test[0,:]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06

In [ ]:
lr.predict([X_test[0,:]])

array([76.90661876])

In [ ]:
lr.predict(X_test)

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [ ]:
Y_test.head()

2435     80.0
3113     40.0
426     120.0
1124     79.0
1161     45.0
Name: price, dtype: float64

In [ ]:
lr.score(X_test,Y_test)

0.790383709268225

#Implementing Ridge and Lasso Regression

In [ ]:
from sklearn.linear_model import Ridge,Lasso

Ridge

In [ ]:
rd = Ridge()

rd.fit(X_train,Y_train)

rd.score(X_test,Y_test)

0.7905686374336628

Lasso

In [ ]:
ls = Lasso()

ls.fit(X_train,Y_train)

ls.score(X_test,Y_test)

0.8036373003525774

In [ ]:
rd2 = Ridge(alpha= 2)

rd2.fit(X_train,Y_train)

rd2.score(X_test,Y_test)

0.7907530260397942

In [ ]:
ls2 = Lasso(alpha=2)

ls2.fit(X_train,Y_train)

ls2.score(X_test,Y_test)

0.8160181533703601

In [ ]:
ls3 = Lasso(alpha=3)

ls3.fit(X_train,Y_train)

ls3.score(X_test,Y_test)

0.8263450613017426

#Model Evaluation

##Root Mean Square Error

In [ ]:
Y_pred = lr.predict(X_test)
Y_pred

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [ ]:
Y_test.head()

2435     80.0
3113     40.0
426     120.0
1124     79.0
1161     45.0
Name: price, dtype: float64

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [ ]:
mse = mean_squared_error(Y_test,Y_pred)
rmse = np.sqrt(mse)

print("Mean_squared_error" , mse)
print("Root mean squared error ", rmse)

Mean_squared_error 4211.806905823333
Root mean squared error  64.8984353110561


# R Square

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(Y_test,Y_pred)

0.790383709268225